### ISSUE TITLE
Missing parameter 'mvn-collect-artifacts-command' in v1.0.3?

### ISSUE THREAD

**Issue by bhamail** [bbottema-circleci/circleci-orbs#4]
I'm trying to get unit test results copied to the 'artifacts/junit' folder by defining the `mvn-collect-artifacts-command`. However, I'm guessing the error I'm seeing is due to this parameter being introduced after version 1.0.3 of  the orb:

```
$ circleci config validate
Error: Error calling workflow: 'workflow'
Error calling job: 'github-maven-deploy/build-and-test'
Unexpected argument(s): mvn-collect-artifacts-command
```

Here's a snippet of my config.yml:

```
version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@1.0.3

mvn-build-test-command: &mvn-build-test-command
  mvn-build-test-command: mvn clean package -PbuildKar

mvn-collect-artifacts-command: &mvn-collect-artifacts-command
  mvn-collect-artifacts-command: mvn validate
    #find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/artifacts/junit/ \;

mvn-deploy-command: &mvn-deploy-command
  mvn-deploy-command: mvn -s .maven.xml clean deploy -PbuildKar -DdeployAtEnd=true -DperformRelease=true -DskipTests -Dspotbugs.skip=true
  context: rso

workflows:
  workflow:
    jobs:
      - github-maven-deploy/build-and-test:
          <<: *mvn-build-test-command
          <<: *mvn-collect-artifacts-command #OPTIONAL

...
```

Is there a "dev" version of this orb I could help test?
Or would you recommend just using an "inline" orb of the latest source? (Or some other approach?). I'm new to these nifty things. Thanks!
